contact_links:
  - name: TrulySimple Community Support
    about: Please ask or answer questions here.
    url: https://github.com/orgs/trulysimple/discussions
  - name: TrulySimple Community Chat
    about: Alternatively, you can join our Discord community.
    url: https://discord.gg/AsDFHUHMpC
